name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, primary]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: See who I am
        run: whoami

      - name: Build Docker
        uses: docker/build-push-action@v2.7.0
        with:
          tags: portfolio
          push: false
      - name: Run Docker
        run: docker run -d portfolio
