name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, primary]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker
        run: docker build -t portfolio .
      - name: Run Docker
        run: docker run -d -p 3000:3000 portfolio
