name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, primary]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Stop Docker
        run: docker stop portfolio
        continue-on-error: true
      - name: Build Docker Image
        run: docker build -t portfolio .
      - name: Start Docker
        run: docker run -d -p 3000:3000 --name portfolio portfolio
