name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    timeout-minutes: 10

    steps:
      - name: Clone Project
        uses: actions/checkout@v3

      - name: Build Service
        run: docker compose build

      - name: Start Service
        run: docker rollout portfolio
